<?php

namespace MailPoetVendor;

if (!defined('ABSPATH')) exit;


// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInitc9dffc041788bd6c8a1e00176978bc3e::getLoader();
